name: sync-fork
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: { }

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo sync $REPOSITORY -b master --force
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_PAT }}
          REPOSITORY: ${{ github.repository }}
      - run: gh repo sync $REPOSITORY -b 4.7 --force
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_PAT }}
          REPOSITORY: ${{ github.repository }}
      - run: gh repo sync $REPOSITORY -b 4.6 --force
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_PAT }}
          REPOSITORY: ${{ github.repository }}
      - run: gh repo sync $REPOSITORY -b 4.5 --force
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_PAT }}
          REPOSITORY: ${{ github.repository }}
